# Week 4 Exercise (group): Exploratory Data Analysis on Social Media Data

- Amitha Bhat
- Ian Huang
- Zekai Wu

## 1. Import necessary packages

In [6]:
# import necessary packages here
!pip install nltk
from nltk import ngrams

Collecting nltk
  Using cached nltk-3.8.1-py3-none-any.whl (1.5 MB)
Collecting click
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.10/site-packages (from nltk) (4.65.0)
Requirement already satisfied: joblib in /opt/conda/lib/python3.10/site-packages (from nltk) (1.2.0)
Collecting regex>=2021.8.3
  Using cached regex-2023.5.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (769 kB)
Installing collected packages: regex, click, nltk
Successfully installed click-8.1.3 nltk-3.8.1 regex-2023.5.5

In [7]:
import pandas as pd

## 2. Read the data

The data is called `tweets.csv` in the same folder. More information about the data see [here](https://www.kaggle.com/datasets/infamouscoder/mental-health-social-media)

The main column you will be working with is `post_text`

In [8]:
df = pd.read_csv("tweets.csv")

# explore the data characteristic using `df.describe()` or `df.info()`

In [39]:
df.describe()

,Unnamed: 0,post_id,user_id,followers,friends,favourites,statuses,retweets,label
count,20000.000000,2.000000e+04,2.000000e+04,20000.000000,20000.000000,20000.000000,2.000000e+04,20000.000000,20000.000000
mean,9999.500000,6.874728e+17,3.548623e+16,900.483950,782.428750,6398.235550,4.439442e+04,1437.927300,0.500000
std,5773.647028,1.708396e+17,1.606083e+17,1899.913961,1834.817945,8393.072914,1.407785e+05,15119.665118,0.500013
min,0.000000,3.555966e+09,1.472438e+07,0.000000,0.000000,0.000000,3.000000e+00,0.000000,0.000000
25%,4999.750000,5.931686e+17,3.242944e+08,177.000000,211.000000,243.000000,5.129000e+03,0.000000,0.000000
50%,9999.500000,7.637400e+17,1.052122e+09,476.000000,561.000000,2752.000000,1.325100e+04,0.000000,0.500000
75%,14999.250000,8.153124e+17,2.285923e+09,1197.000000,701.000000,8229.000000,5.289200e+04,1.000000,1.000000
max,19999.000000,8.194574e+17,7.631825e+17,28614.000000,28514.000000,39008.000000,1.063601e+06,839540.000000,1.000000

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    20000 non-null  int64
 1   post_id       20000 non-null  int64
 2   post_created  20000 non-null  object
 3   post_text     20000 non-null  object
 4   user_id       20000 non-null  int64
 5   followers     20000 non-null  int64
 6   friends       20000 non-null  int64
 7   favourites    20000 non-null  int64
 8   statuses      20000 non-null  int64
 9   retweets      20000 non-null  int64
 10  label         20000 non-null  int64
 11  emojis        20000 non-null  object
dtypes: int64(9), object(3)
memory usage: 1.8+ MB

## 3. Extract emojis

Use `emoji` package to extract emojis and put them into a new column called `emojis`

In [41]:
# define the function
!pip install emoji
import emoji

# apply the function to your dataframe

Requirement already satisfied: emoji in /opt/conda/lib/python3.10/site-packages (2.2.0)

In [58]:
# emojis = []
# for c in df['post_text']:
#     emojis.append(emoji.distinct_emoji_list(c))

# df['emojis'] = emojis

def extract_distinct_emojis(post_text):
    return emoji.distinct_emoji_list(post_text)

In [60]:
df['emojis'] = df['post_text'].apply(extract_distinct_emojis)
df

,Unnamed: 0,post_id,post_created,post_text,user_id,followers,friends,favourites,statuses,retweets,label,emojis
0,0,637894677824413696,Sun Aug 30 07:48:37 +0000 2015,It's just over 2 years since I was diagnosed w...,1013187241,84,211,251,837,0,1,[]
1,1,637890384576778240,Sun Aug 30 07:31:33 +0000 2015,"It's Sunday, I need a break, so I'm planning t...",1013187241,84,211,251,837,1,1,[]
2,2,637749345908051968,Sat Aug 29 22:11:07 +0000 2015,Awake but tired. I need to sleep but my brain ...,1013187241,84,211,251,837,0,1,[]
3,3,637696421077123073,Sat Aug 29 18:40:49 +0000 2015,RT @SewHQ: #Retro bears make perfect gifts and...,1013187241,84,211,251,837,2,1,[]
4,4,637696327485366272,Sat Aug 29 18:40:26 +0000 2015,It’s hard to say whether packing lists are mak...,1013187241,84,211,251,837,1,1,[]
...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,819336825231773698,Thu Jan 12 00:14:56 +0000 2017,A day without sunshine is like night.,1169875706,442,230,7,1063601,0,0,[]
19996,19996,819334654260080640,Thu Jan 12 00:06:18 +0000 2017,"Boren's Laws: (1) When in charge, ponder. (2) ...",1169875706,442,230,7,1063601,0,0,[]
19997,19997,819334503042871297,Thu Jan 12 00:05:42 +0000 2017,The flow chart is a most thoroughly oversold p...,1169875706,442,230,7,1063601,0,0,[]
19998,19998,819334419374899200,Thu Jan 12 00:05:22 +0000 2017,"Ships are safe in harbor, but they were never ...",1169875706,442,230,7,1063601,0,0,[]
19999,19999,819334270825197568,Thu Jan 12 00:04:47 +0000 2017,Black holes are where God is dividing by zero.,1169875706,442,230,7,1063601,0,0,[]

## 4. Text Cleaning using Regular Expressions 

1. Remove URLs
2. Remove mentions
3. Remove hashtags
4. Remove special characters
5. Remove extra space

Code can be found in [week 6 lecture 1](https://github.com/yibeichan/COMM160DS/blob/main/week_6/lecture_part1.ipynb) section `4.4 All-in-One`

Perform the analysis and save the results into a new column.

In [65]:
# define the function
import re
def clean_text(text):
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'#\w+', '', text)
    text = re.sub(r'\W', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

df["cleaned_text"] = df['post_text'].apply(clean_text)
df["cleaned_text"]

0        It s just over 2 years since I was diagnosed w...
1        It s Sunday I need a break so I m planning to ...
2        Awake but tired I need to sleep but my brain h...
3        RT bears make perfect gifts and are great for ...
4        It s hard to say whether packing lists are mak...
                               ...
19995                 A day without sunshine is like night
19996    Boren s Laws 1 When in charge ponder 2 When in...
19997    The flow chart is a most thoroughly oversold p...
19998    Ships are safe in harbor but they were never m...
19999        Black holes are where God is dividing by zero
Name: cleaned_text, Length: 20000, dtype: object

In [66]:
df

,Unnamed: 0,post_id,post_created,post_text,user_id,followers,friends,favourites,statuses,retweets,label,emojis,cleaned_text
0,0,637894677824413696,Sun Aug 30 07:48:37 +0000 2015,It's just over 2 years since I was diagnosed w...,1013187241,84,211,251,837,0,1,[],It s just over 2 years since I was diagnosed w...
1,1,637890384576778240,Sun Aug 30 07:31:33 +0000 2015,"It's Sunday, I need a break, so I'm planning t...",1013187241,84,211,251,837,1,1,[],It s Sunday I need a break so I m planning to ...
2,2,637749345908051968,Sat Aug 29 22:11:07 +0000 2015,Awake but tired. I need to sleep but my brain ...,1013187241,84,211,251,837,0,1,[],Awake but tired I need to sleep but my brain h...
3,3,637696421077123073,Sat Aug 29 18:40:49 +0000 2015,RT @SewHQ: #Retro bears make perfect gifts and...,1013187241,84,211,251,837,2,1,[],RT bears make perfect gifts and are great for ...
4,4,637696327485366272,Sat Aug 29 18:40:26 +0000 2015,It’s hard to say whether packing lists are mak...,1013187241,84,211,251,837,1,1,[],It s hard to say whether packing lists are mak...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,819336825231773698,Thu Jan 12 00:14:56 +0000 2017,A day without sunshine is like night.,1169875706,442,230,7,1063601,0,0,[],A day without sunshine is like night
19996,19996,819334654260080640,Thu Jan 12 00:06:18 +0000 2017,"Boren's Laws: (1) When in charge, ponder. (2) ...",1169875706,442,230,7,1063601,0,0,[],Boren s Laws 1 When in charge ponder 2 When in...
19997,19997,819334503042871297,Thu Jan 12 00:05:42 +0000 2017,The flow chart is a most thoroughly oversold p...,1169875706,442,230,7,1063601,0,0,[],The flow chart is a most thoroughly oversold p...
19998,19998,819334419374899200,Thu Jan 12 00:05:22 +0000 2017,"Ships are safe in harbor, but they were never ...",1169875706,442,230,7,1063601,0,0,[],Ships are safe in harbor but they were never m...
19999,19999,819334270825197568,Thu Jan 12 00:04:47 +0000 2017,Black holes are where God is dividing by zero.,1169875706,442,230,7,1063601,0,0,[],Black holes are where God is dividing by zero

## 5. Analysis 1 (Rename the title with your chosen analysis)

Choose one analysis from (1)Sentiment Analysis, (2)N-grams and Phrase Analysis, (3)Collocation Analysis, (4)Part-of-Speech Tagging, (5)Named Entity Recognition, and (6)Dependency Parsing.

Perform the analysis and save the results into a new column.

In [68]:
!pip install textblob

Collecting textblob
  Using cached textblob-0.17.1-py2.py3-none-any.whl (636 kB)
Requirement already satisfied: nltk>=3.1 in /opt/conda/lib/python3.10/site-packages (from textblob) (3.8.1)
Requirement already satisfied: joblib in /opt/conda/lib/python3.10/site-packages (from nltk>=3.1->textblob) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /opt/conda/lib/python3.10/site-packages (from nltk>=3.1->textblob) (2023.5.5)
Requirement already satisfied: click in /opt/conda/lib/python3.10/site-packages (from nltk>=3.1->textblob) (8.1.3)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.10/site-packages (from nltk>=3.1->textblob) (4.65.0)
Installing collected packages: textblob
Successfully installed textblob-0.17.1

In [71]:
# write your code here
from textblob import TextBlob

def get_sentiment(text):
    analysis = TextBlob(text)
    if analysis.sentiment.polarity > 0:
        return 'positive'
    elif analysis.sentiment.polarity == 0:
        return 'neutral'
    else:
        return 'negative'
    
df["get_sentiment"] = df['post_text'].apply(get_sentiment)
df["get_sentiment"]

0        positive
1        negative
2        negative
3        positive
4        negative
           ...
19995     neutral
19996    negative
19997    positive
19998    positive
19999    negative
Name: get_sentiment, Length: 20000, dtype: object

In [72]:
df

,Unnamed: 0,post_id,post_created,post_text,user_id,followers,friends,favourites,statuses,retweets,label,emojis,cleaned_text,get_sentiment
0,0,637894677824413696,Sun Aug 30 07:48:37 +0000 2015,It's just over 2 years since I was diagnosed w...,1013187241,84,211,251,837,0,1,[],It s just over 2 years since I was diagnosed w...,positive
1,1,637890384576778240,Sun Aug 30 07:31:33 +0000 2015,"It's Sunday, I need a break, so I'm planning t...",1013187241,84,211,251,837,1,1,[],It s Sunday I need a break so I m planning to ...,negative
2,2,637749345908051968,Sat Aug 29 22:11:07 +0000 2015,Awake but tired. I need to sleep but my brain ...,1013187241,84,211,251,837,0,1,[],Awake but tired I need to sleep but my brain h...,negative
3,3,637696421077123073,Sat Aug 29 18:40:49 +0000 2015,RT @SewHQ: #Retro bears make perfect gifts and...,1013187241,84,211,251,837,2,1,[],RT bears make perfect gifts and are great for ...,positive
4,4,637696327485366272,Sat Aug 29 18:40:26 +0000 2015,It’s hard to say whether packing lists are mak...,1013187241,84,211,251,837,1,1,[],It s hard to say whether packing lists are mak...,negative
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,819336825231773698,Thu Jan 12 00:14:56 +0000 2017,A day without sunshine is like night.,1169875706,442,230,7,1063601,0,0,[],A day without sunshine is like night,neutral
19996,19996,819334654260080640,Thu Jan 12 00:06:18 +0000 2017,"Boren's Laws: (1) When in charge, ponder. (2) ...",1169875706,442,230,7,1063601,0,0,[],Boren s Laws 1 When in charge ponder 2 When in...,negative
19997,19997,819334503042871297,Thu Jan 12 00:05:42 +0000 2017,The flow chart is a most thoroughly oversold p...,1169875706,442,230,7,1063601,0,0,[],The flow chart is a most thoroughly oversold p...,positive
19998,19998,819334419374899200,Thu Jan 12 00:05:22 +0000 2017,"Ships are safe in harbor, but they were never ...",1169875706,442,230,7,1063601,0,0,[],Ships are safe in harbor but they were never m...,positive
19999,19999,819334270825197568,Thu Jan 12 00:04:47 +0000 2017,Black holes are where God is dividing by zero.,1169875706,442,230,7,1063601,0,0,[],Black holes are where God is dividing by zero,negative

## 6. Analysis 2 (Rename the title with your chosen analysis)

Choose another analysis from (1)Sentiment Analysis, (2)N-grams and Phrase Analysis, (3)Collocation Analysis, (4)Part-of-Speech Tagging, (5)Named Entity Recognition, and (6)Dependency Parsing.

Perform the analysis and save the results into a new column.

In [75]:
!pip install nltk
from nltk import ngrams

3686.05s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Requirement already satisfied: nltk in /opt/conda/lib/python3.10/site-packages (3.8.1)
Requirement already satisfied: joblib in /opt/conda/lib/python3.10/site-packages (from nltk) (1.2.0)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.10/site-packages (from nltk) (4.65.0)
Requirement already satisfied: click in /opt/conda/lib/python3.10/site-packages (from nltk) (8.1.3)
Requirement already satisfied: regex>=2021.8.3 in /opt/conda/lib/python3.10/site-packages (from nltk) (2023.5.5)

In [78]:
def generate_ngrams(text, n):
    tokens = text.split()
    return list(ngrams(tokens, n))

df["bigrams"] = df['post_text'].apply(generate_ngrams, n=5)
df["bigrams"]

0        [(It's, just, over, 2, years), (just, over, 2,...
1        [(It's, Sunday,, I, need, a), (Sunday,, I, nee...
2        [(Awake, but, tired., I, need), (but, tired., ...
3        [(RT, @SewHQ:, #Retro, bears, make), (@SewHQ:,...
4        [(It’s, hard, to, say, whether), (hard, to, sa...
                               ...
19995    [(A, day, without, sunshine, is), (day, withou...
19996    [(Boren's, Laws:, (1), When, in), (Laws:, (1),...
19997    [(The, flow, chart, is, a), (flow, chart, is, ...
19998    [(Ships, are, safe, in, harbor,), (are, safe, ...
19999    [(Black, holes, are, where, God), (holes, are,...
Name: bigrams, Length: 20000, dtype: object

In [79]:
df

,Unnamed: 0,post_id,post_created,post_text,user_id,followers,friends,favourites,statuses,retweets,label,emojis,cleaned_text,get_sentiment,bigrams
0,0,637894677824413696,Sun Aug 30 07:48:37 +0000 2015,It's just over 2 years since I was diagnosed w...,1013187241,84,211,251,837,0,1,[],It s just over 2 years since I was diagnosed w...,positive,"[(It's, just, over, 2, years), (just, over, 2,..."
1,1,637890384576778240,Sun Aug 30 07:31:33 +0000 2015,"It's Sunday, I need a break, so I'm planning t...",1013187241,84,211,251,837,1,1,[],It s Sunday I need a break so I m planning to ...,negative,"[(It's, Sunday,, I, need, a), (Sunday,, I, nee..."
2,2,637749345908051968,Sat Aug 29 22:11:07 +0000 2015,Awake but tired. I need to sleep but my brain ...,1013187241,84,211,251,837,0,1,[],Awake but tired I need to sleep but my brain h...,negative,"[(Awake, but, tired., I, need), (but, tired., ..."
3,3,637696421077123073,Sat Aug 29 18:40:49 +0000 2015,RT @SewHQ: #Retro bears make perfect gifts and...,1013187241,84,211,251,837,2,1,[],RT bears make perfect gifts and are great for ...,positive,"[(RT, @SewHQ:, #Retro, bears, make), (@SewHQ:,..."
4,4,637696327485366272,Sat Aug 29 18:40:26 +0000 2015,It’s hard to say whether packing lists are mak...,1013187241,84,211,251,837,1,1,[],It s hard to say whether packing lists are mak...,negative,"[(It’s, hard, to, say, whether), (hard, to, sa..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,19995,819336825231773698,Thu Jan 12 00:14:56 +0000 2017,A day without sunshine is like night.,1169875706,442,230,7,1063601,0,0,[],A day without sunshine is like night,neutral,"[(A, day, without, sunshine, is), (day, withou..."
19996,19996,819334654260080640,Thu Jan 12 00:06:18 +0000 2017,"Boren's Laws: (1) When in charge, ponder. (2) ...",1169875706,442,230,7,1063601,0,0,[],Boren s Laws 1 When in charge ponder 2 When in...,negative,"[(Boren's, Laws:, (1), When, in), (Laws:, (1),..."
19997,19997,819334503042871297,Thu Jan 12 00:05:42 +0000 2017,The flow chart is a most thoroughly oversold p...,1169875706,442,230,7,1063601,0,0,[],The flow chart is a most thoroughly oversold p...,positive,"[(The, flow, chart, is, a), (flow, chart, is, ..."
19998,19998,819334419374899200,Thu Jan 12 00:05:22 +0000 2017,"Ships are safe in harbor, but they were never ...",1169875706,442,230,7,1063601,0,0,[],Ships are safe in harbor but they were never m...,positive,"[(Ships, are, safe, in, harbor,), (are, safe, ..."
19999,19999,819334270825197568,Thu Jan 12 00:04:47 +0000 2017,Black holes are where God is dividing by zero.,1169875706,442,230,7,1063601,0,0,[],Black holes are where God is dividing by zero,negative,"[(Black, holes, are, where, God), (holes, are,..."

## 7. Push Your Results to GitHub

As you did in previous weeks:
1. `git status`
2. `git add`
3. `git commit -m "type your message here"`
4. `git push`

If you can't push it to GitHub, it's okay to manually uploaded it.